### PR TITLE
fix: replace TaskGroup with PersistentTaskGroup in process_lifecycle_events to prevent TERMINATING stuck issue

### PR DESCRIPTION
**Pull request by adrysn**

### CODE REVIEW

**Comment by adrysn** [comment]
This is not the actual cause of the problem. We need to investigate further.

**Comment by adrysn** [comment]
When I tested this changes in my test machine, the `TERMINATING` stuck issue does not appear any more. I think it's good to merge this PR.

**Comment by fregataa** [comment]
I guess the major difference between TaskGroup and PersistentTaskGroup is that TaskGroup is managed with parent task and PersistentTaskGroup is not. that can be a reason TERMINATING issue occurs?

**Comment by achimnol** [comment]
> I guess the major difference between TaskGroup and PersistentTaskGroup is that TaskGroup is managed with parent task and PersistentTaskGroup is not. that can be a reason TERMINATING issue occurs?

`TaskGroup` "aborts" (=cancel all running tasks) if any one of its tasks raises unhandled exception, while `PersistentTaskGroup` keeps running but just calls the designated exception handler.

**Pull request merged**
